title: "<gradient:#aa3159:#8c0c0c>HMCColor"
blacklistedItems:
  oraxen_items:
    - banned_oraxen_id
  itemsadder_items:
    - banned_itemsadder_id
  types:
    - LEATHER_CHESTPLATE
colors:
  red:
    baseColor: 190,20,20
    subColors:
      - "#FF0000"
      - "#CE2029"
      - "66023C"
      - "C71585"
      - "B3446C"
      - "DE3163"
      - "FF6961"
  orange:
    baseColor: 234,92,43
    subColors:
      - "#FF9F00"
      - "#FFA500"
      - "#F28500"
      - "#FFB347"
      - "#E24C00"
      - "#EC5800"
      - "#FFA500"
  yellow:
    baseColor: 255,201,0
    subColors:
      - "#FDDE6C"
      - "#FFF44F"
      - "#FFEF00"
      - "#FFD00A"
      - "#F1FF62"
      - "#E8DE2A"
      - "#FFD800"
  pink:
    baseColor: "#FC35FA"
    subColors:
      - "#FC8EAC"
      - "#FC6C85"
      - "#FF77FF"
      - "#FF69B4"
      - "#E75480"
      - "#FFD1DC"
      - "#8c0c1c"
      - "#DE5D83"
  white:
    baseColor: 255,255,255
    subColors:
      - "#FFFFFF"
      - "#FDF5E6"
      - "#FAF0E6"
      - "#F5F5F5"
      - "#808080"
      - "#2A2727"
      - "#000000"
  green:
    baseColor: 163,218,141
    subColors:
      - "#32CD32"
      - "#4CBB17"
      - "#7FFF00"
      - "#006400"
      - "#228B22"
      - "#39FF14"
      - "#4F7942"
  purple:
    baseColor: 137,70,166
    subColors:
      - "#9966CC"
      - "#4B0082"
      - "#551A8B"
      - "#6F2DA8"
      - "#BF00FF"
      - "#7851A9"
      - "#B666D2"
  blue:
    baseColor: 55,49,181
    subColors:
      - "#318CE7"
      - "#034694"
      - "#007FFF"
      - "#0000FF"
      - "#13274F"
      - "#00008B"
      - "#6495ED"
  aqua:
    baseColor: "#99FFFF"
    subColors:
      - "#0CAFFF"
      - "#0CBFFF"
      - "#7DF9FF"
      - "#87CEFA"
      - "#73C2FB"
      - "#7CB9E8"
      - "#99FFFF"
