title: "<gradient:#aa3159:#8c0c0c>HMCColor"
buttons:
  #oraxen_item: something
  #itemsadder_item: something:something
  default_type: LEATHER_HORSE_ARMOR #Can also be POTION to avoid conflicts with ModelEngine
  custom_model_data: 10 #Only important if using default_type
blacklistedItems:
  oraxen_items:
    - banned_oraxen_id
  itemsadder_items:
    - banned_itemsadder_id
  types:
    - LEATHER_CHESTPLATE
colors:
  red:
    name: "Red"
    baseColor: 190,20,20
    subColors:
      1:
        name: "sadasd"
        color: "#FF0000"
      2:
        name: "sadasd"
        color: "#CE2029"
      3:
        name: "sadasd"
        color: "66023C"
      4:
        name: "sadasd"
        color: "C71585"
      5:
        name: "sadasd"
        color: "B3446C"
      6:
        name: "sadasd"
        color: "DE3163"
      7:
        name: "sadasd"
        color: "FF6961"
  orange:
    name: "Orange"
    baseColor: 234,92,43
    subColors:
      1:
        name: "sadasd"
        color: "#FF9F00"
      2:
        name: "sadasd"
        color: "#FFA500"
      3:
        name: "sadasd"
        color: "#F28500"
      4:
        name: "sadasd"
        color: "#FFB347"
      5:
        name: "sadasd"
        color: "#E24C00"
      6:
        name: "sadasd"
        color: "#EC5800"
      7:
        name: "sadasd"
        color: "#FFA500"
  yellow:
    name: "Yellow"
    baseColor: 255,201,0
    subColors:
      1:
        name: "sadasd"
        color: "#FDDE6C"
      2:
        name: "sadasd"
        color: "#FFF44F"
      3:
        name: "sadasd"
        color: "#FFEF00"
      4:
        name: "sadasd"
        color: "#FFD00A"
      5:
        name: "sadasd"
        color: "#F1FF62"
      6:
        name: "sadasd"
        color: "#E8DE2A"
      7:
        name: "sadasd"
        color: "#FFD800"
  pink:
    name: "Pink"
    baseColor: "#FC35FA"
    subColors:
      1:
        name: "sadasd"
        color: "#FC8EAC"
      2:
        name: "sadasd"
        color: "#FC6C85"
      3:
        name: "sadasd"
        color: "#FF77FF"
      4:
        name: "sadasd"
        color: "#FF69B4"
      5:
        name: "sadasd"
        color: "#E75480"
      6:
        name: "sadasd"
        color: "#FFD1DC"
      7:
        name: "sadasd"
        color: "#8c0c1c"
  white:
    name: "White"
    baseColor: 255,255,255
    subColors:
      1:
        name: "sadasd"
        color: "#FFFFFF"
      2:
        name: "sadasd"
        color: "#FDF5E6"
      3:
        name: "sadasd"
        color: "#FAF0E6"
      4:
        name: "sadasd"
        color: "#F5F5F5"
      5:
        name: "sadasd"
        color: "#808080"
      6:
        name: "sadasd"
        color: "#2A2727"
      7:
        name: "sadasd"
        color: "#000000"
  green:
    name: "Green"
    baseColor: 163,218,141
    subColors:
      1:
        name: "sadasd"
        color: "#32CD32"
      2:
        name: "sadasd"
        color: "#4CBB17"
      3:
        name: "sadasd"
        color: "#7FFF00"
      4:
        name: "sadasd"
        color: "#006400"
      5:
        name: "sadasd"
        color: "#228B22"
      6:
        name: "sadasd"
        color: "#39FF14"
      7:
        name: "sadasd"
        color: "#4F7942"
  purple:
    name: "Purple"
    baseColor: 137,70,166
    subColors:
      1:
        name: "sadasd"
        color: "#9966CC"
      2:
        name: "sadasd"
        color: "#4B0082"
      3:
        name: "sadasd"
        color: "#551A8B"
      4:
        name: "sadasd"
        color: "#6F2DA8"
      5:
        name: "sadasd"
        color: "#BF00FF"
      6:
        name: "sadasd"
        color: "#7851A9"
      7:
        name: "sadasd"
        color: "#B666D2"
  blue:
    name: "Blue"
    baseColor: 55,49,181
    subColors:
      1:
        name: "sadasd"
        color: "#318CE7"
      2:
        name: "sadasd"
        color: "#034694"
      3:
        name: "sadasd"
        color: "#007FFF"
      4:
        name: "sadasd"
        color: "#0000FF"
      5:
        name: "sadasd"
        color: "#13274F"
      6:
        name: "sadasd"
        color: "#00008B"
      7:
        name: "sadasd"
        color: "#6495ED"
  aqua:
    name: "Aqua"
    baseColor: "#99FFFF"
    subColors:
      1:
        name: "sadasd"
        color: "#0CAFFF"
      2:
        name: "sadasd"
        color: "#0CBFFF"
      3:
        name: "sadasd"
        color: "#7DF9FF"
      4:
        name: "sadasd"
        color: "#87CEFA"
      5:
        name: "sadasd"
        color: "#73C2FB"
      6:
        name: "sadasd"
        color: "#7CB9E8"
      7:
        name: "sadasd"
        color: "#99FFFF"
